### ISSUE TITLE
微信小程序表格没有边框

### ISSUE THREAD

**Issue by keke122765** [gaoyia/parse#8]
![image](https://user-images.githubusercontent.com/44694221/61776553-ddd50f80-ae2d-11e9-900e-0680c2382737.png)

**Comment by plfqz** [comment]
我通过修改他的内部组件实现了效果 思路是 在他每一个转译的组件内 用view套一下 增加class wxParse 
同时在对应组件下引入wxParse.css 成功的出现了表格样式

`<template>
	<view class="wxParse">
		<rich-text :nodes="nodes"></rich-text>
	</view>
</template>`

`<style>
	@import url("../parse.css");
</style>`

**Comment by plfqz** [comment]
期待作者更新

**Comment by gaoyia** [comment]
感谢，下版就修复
